AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required]
        public String Name { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "This is not a valid email address")]
        public String Email { get; set; }

        [Required]
        public String Subject { get; set; }

        [Required]
        public String Message { get; set; }
    }
}

AarhusWebDevCoop/ViewModels/MessageForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevCoop.ViewModels
{
    public class MessageForm
    {
        [Required(ErrorMessage = "The Name field is required.")]
        public String mesName { get; set; }

        [Required(ErrorMessage = "The Email field is required.")]
        [EmailAddress(ErrorMessage = "This is not a valid email address")]
        public String mesEmail { get; set; }

        [Required(ErrorMessage = "The Title field is required.")]
        public String mesTitle { get; set; }

        [Required(ErrorMessage = "The Message field is required.")]
        public String mesMessage { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index() {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm contact) {
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            // Insert the data in the Umbraco System - The string names in setvalues are the
            // aliases from the Comment document type properties
            IContent comment = Services.ContentService.CreateContent(contact.Subject, CurrentPage.Id, "comment");
            comment.SetValue("cName", contact.Name);
            comment.SetValue("cEmail", contact.Email);
            comment.SetValue("cSubject", contact.Subject);
            comment.SetValue("cMessage", contact.Message);
            Services.ContentService.Save(comment); // Saving


            // Create an email to be sent to the editor (Currently deactivated)
            MailMessage message = new MailMessage();
            message.To.Add("eaamamad14@gmail.com");
            message.Subject = contact.Subject;
            message.From = new MailAddress(contact.Email, contact.Name);
            message.Body = contact.Message + "\n my email is: " + contact.Email;

            using (SmtpClient smtp = new SmtpClient()) {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("eaamamad14@gmail.com", "testingApps");
                smtp.EnableSsl = true;

                // Send Mail
                TempData["success"] = true;
                //smtp.Send(message);
            }

            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Controllers/MessageFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using AarhusWebDevCoop.ViewModels;

namespace AarhusWebDevCoop.Controllers
{
    public class MessageFormSurfaceController : SurfaceController
    {
        // GET: MessageFormSurface
        public ActionResult Index() {
            return PartialView("MessageForm", new MessageForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(MessageForm message) {
           if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            // Insert the data in the Umbraco System
            // Parameters: The "headline" on the list in backend office, the node the list
            // should be shown and the Document Type that the message should be inserted into
            IContent userMessage = Services.ContentService.CreateContent(message.mesTitle, CurrentPage.Id, "Message");
            userMessage.SetValue("mName", message.mesName);
            userMessage.SetValue("mEmail", message.mesEmail);
            userMessage.SetValue("mTitle", message.mesTitle);
            userMessage.SetValue("mMessage", message.mesMessage);
            Services.ContentService.Save(userMessage); // only saving, but does not publish it

            TempData["success"] = true;

            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4 about-us">
    <!-- The Grid Layout for the About Us page -->
    @CurrentPage.GetGridHtml("gridLayout")
</article>

AarhusWebDevCoop/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4 articles-projects">
    
    <!-- News Content -->
    @Umbraco.Field("articleItemContent")
    
    <!-- News Footer with info about author -->
    <footer class="container-fluid text-center bg-light py-4 my-4 border">
        <p class="font-weight-bold mb-0">Posted:</p>
        <p>@Model.Content.CreateDate.ToString("d MMM yyyy"), @Model.Content.CreateDate.ToString("HH:mm")</p>
        
        <p class="font-weight-bold mb-0">Author:</p> 
        <p>@Umbraco.Field("articleAuthor") / <a href="@Umbraco.Field("articleReadMoreLink")">@Umbraco.Field("articleReadMoreTitle")</a></p>
    </footer>
</article>

<!-- To the next or previous article -->
<section class="container-fluid w-100 bg-light mb-0 py-4">
    <article class="pb-0">
        <h2 class="text-center">Hungry for more news?</h2>
        <p class="text-center">Navigate to the next article or maybe go back to the previous.</p>
        @Umbraco.RenderMacro("nextArticle")</article>
</section>

AarhusWebDevCoop/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4">
    
    <!-- News Main Page Description -->
    @Umbraco.Field("articlesListDescription")
    
    <!-- List of News Articles -->
    <h2 class="text-center mt-5 mb-4">All the articles</h2>
    @Umbraco.RenderMacro("listArticles")
    
</articles>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4">
    <section>
        <!-- Description of the Contact page -->
        <div class="container p-0">
            @Umbraco.Field("contactDescription")
        </div>
        
        <!-- The Contact Form (added with Child Action) -->
        <h2>Write to us</h2>
        @Html.Action("Index", "ContactFormSurface")
    </section>
</article>

AarhusWebDevCoop/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4">
    
    <!-- Description of Website -->
    <section>
        <h2>@Umbraco.Field("homeTitle")</h2>
        <div class="container-fluid mx-0 px-0 my-4">@Umbraco.Field("homeContent")</div>
    </section>
    
    <!-- List of Newest Completed Projects -->
    <section>
        <h2 class="my-4">Newest Completed Projects</h2>
        @Umbraco.RenderMacro("newestCompletedProjects", new {numOfProjects="2"})
    </section>

    <!-- List of Newest Articles -->
    <section>
        <h2 class="my-4">Newest Articles</h2>
        @Umbraco.RenderMacro("newestArticles", new {numOfArticles="3"})
    </section>
</article>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{ Layout = "Master.cshtml"; }

<article class="my-4">
    
    <!-- Checking if a Member is logged in or not -->
    @if (!Members.GetCurrentLoginStatus().IsLoggedIn) {
        <!-- If not logged in then the login page -->
        @Html.Partial("Login")
    } else {
        <!-- If logged in then the logout page -->
        @Html.Partial("Logout")
    }
    
</article>

AarhusWebDevCoop/Views/MacroPartials/Articles/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{
// VARIABLES containing the articles and different images
var articleList = Model.Content.Site().FirstChild("articlesMain").Children()
					.Where(x => x.IsVisible())
					.OrderBy("CreateDate desc");
var standardImage = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImage"); 
var standardImageArticles = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageArticles"); 
var showStandardImageArticles = Model.Content.Site().GetPropertyValue<Boolean>("showStandardImageArticles");
}

<div class="container-fluid m-0 p-0">
        @foreach (var article in articleList) {
            
        <!-- Finding the main image of specific article -->    
        var mainImage = article.GetPropertyValue<IPublishedContent>("articleItemMainImage");
        var image = (mainImage != null) 
                        ? mainImage 
                        : showStandardImageArticles == true 
                        ? standardImageArticles != null 
                        ? standardImageArticles 
                        : standardImage
                        : standardImage;
        
        <!-- ARTICLE LIST -->
        <div class="article-list row my-3">
                    
            <!-- ARTICLE IMAGE -->
            <div class="col-md-4 bg-light p-0 articles-projects-list">
                <a href="@article.Url"><img src="@image.Url" alt="@image.Name" /></a>
            </div> <!-- end of column -->
                
            <!-- ARTICLE INFO (Title, Teaser, Read More) -->
            <div class="col-md-8 bg-light py-2 articles-projects-info">
                <h3><a href="@article.Url">@(article.GetPropertyValue<String>("articleItemTitle"))</a></h3>
                <p class="m-0 mb-1 p-0 article-project-dates text-secondary">@article.CreateDate.ToString("d MMM yyyy"), @article.CreateDate.ToString("HH:mm")</p>
                <p class="m-0 p-0">@Umbraco.Truncate(article.GetPropertyValue<String>("articleItemContent"), 150, true)</p>
                <a href="@article.Url">Read more</a>
            </div> <!-- end of column -->
                
        </div> <!-- end of row -->
    }
</div> <!-- end of container -->

AarhusWebDevCoop/Views/MacroPartials/Articles/newestArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
// VARIABLES containing the articles and different images
var numOfArticles = Model.MacroParameters["numOfArticles"];
var standardImageArticles = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageArticles");
var showStandardImageArticles = Model.Content.Site().GetPropertyValue<Boolean>("showStandardImageArticles");
var standardImage = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImage");
var newestArticles =
    Model.Content.Site().FirstChild("articlesMain").Children()
    .Where(x => x.IsVisible())
    .OrderBy("CreateDate desc")
    .Take(Convert.ToInt32(numOfArticles));
}

<div class="container-fluid m-0 p-0">
     
    @foreach (var article in newestArticles) {

        <!-- Finding the main image of specific article -->    
        var mainImage = article.GetPropertyValue<IPublishedContent>("articleItemMainImage");
        var image = (mainImage != null) 
                        ? mainImage 
                        : showStandardImageArticles == true 
                        ? standardImageArticles != null 
                        ? standardImageArticles 
                        : standardImage
                        : standardImage;
        
        <!-- ARTICLE LIST -->
        <div class="article-list row my-3">
                    
            <!-- ARTICLE IMAGE -->
            <div class="col-md-4 bg-light p-0 articles-projects-list">
                <a href="@article.Url"><img src="@image.Url" alt="@image.Name" /></a>
            </div> <!-- end of column -->
                
            <!-- ARTICLE INFO (Title, Teaser, Read More) -->
            <div class="col-md-8 bg-light py-2 articles-projects-info">
                <h3><a href="@article.Url">@(article.GetPropertyValue<String>("articleItemTitle"))</a></h3>
                <p class="m-0 mb-1 p-0 article-project-dates text-secondary">@article.CreateDate.ToString("d MMM yyyy"), @article.CreateDate.ToString("HH:mm")</p>
                <p class="m-0 p-0">@Umbraco.Truncate(article.GetPropertyValue<String>("articleItemContent"), 150, true)</p>
                <a href="@article.Url">Read more</a>
            </div> <!-- end of column -->
                
        </div> <!-- end of row -->
    }
</div> <!-- end of container -->

AarhusWebDevCoop/Views/MacroPartials/Header/findHeaderImages.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
// VARIABLES containing Images and finding the right images
var projectImage = Model.Content.GetPropertyValue<IPublishedContent>("projectItemMainImage"); 
var articleImage = Model.Content.GetPropertyValue<IPublishedContent>("articleItemMainImage"); 
var standardImage = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImage"); 
var standardImageProjects = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageProjects"); 
var showStandardImageProjects = Model.Content.Site().GetPropertyValue<Boolean>("showStandardImageProjects"); 
var standardImageNews = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageArticles"); 
var showStandardImageNews = Model.Content.Site().GetPropertyValue<Boolean>("showstandardImageArticles");
var findProjectImage = projectImage != null 
        ? projectImage 
        : showStandardImageProjects == true 
        ? standardImageProjects != null 
        ? standardImageProjects 
        : standardImage 
        : standardImage;
var findArticleImage = articleImage != null 
        ? articleImage 
        : showStandardImageNews == true 
        ? standardImageNews != null 
        ? standardImageNews 
        : standardImage 
        : standardImage;
}

<!-- Finding the header image to the document type respectively -->
@if(Model.Content.DocumentTypeAlias == "projectsItem") {
    <img class="justify-content-center" src="@findProjectImage.Url" alt="@findProjectImage.Name" >
} else if(Model.Content.DocumentTypeAlias == "articlesItem") {
    <img class="justify-content-center" src="@findArticleImage.Url" alt="@findArticleImage.Name">
} else {
    <img class="justify-content-center" src="@standardImage.Url" alt="@standardImage.Name" />
}

AarhusWebDevCoop/Views/MacroPartials/Header/header.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

<!-- HEADER -->
<header class="main-header container-fluid p-0">
    
    <!-- Image Overlay -->
    <div class="header-overlay bg-dark h-100 w-100 position-absolute"></div>
    
    <!-- Main Image -->
    @Umbraco.RenderMacro("findHeaderImages")
    
    <!-- Page Info -->
    <div class="page-title m-0 p-0 text-uppercase text-light">
        
        <!-- If document type is projectItem or Article Item the parent name should be shown -->    
        @if (Model.Content.DocumentTypeAlias == "projectsItem" || Model.Content.DocumentTypeAlias == "articlesItem") {
            <a href="@Model.Content.Up().Url" class="p-0 m-0 text-light">@Model.Content.Up().Name</a>
        }
        
        <!-- Title -->  
        <h1 class="p-0 mt-2 mb-2">@(Model.Content.Name == "Home" ? "Aarhus Web Developer Consortium" : Model.Content.Name)</h1>
    </div>
    
</header> <!-- end of container -->

AarhusWebDevCoop/Views/MacroPartials/Projects/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{
// VARIABLES containing project list and images
var projectList = Model.Content.Site().FirstChild("projectsMain").Children()
					.Where(x => x.IsVisible())
					.OrderBy("CreateDate desc");
var standardImageProjects = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageProjects");
var showStandardImageProjects = Model.Content.Site().GetPropertyValue<Boolean>("showStandardImageProjects");
var standardImage = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImage");
}

<div class="container-fluid m-0 p-0">
     
    @foreach (var project in projectList) {
            
        <!-- Finding the main image and the status of specific project -->    
        var mainImage = project.GetPropertyValue<IPublishedContent>("projectItemMainImage");
        var image = mainImage != null 
                    ? mainImage 
                    : showStandardImageProjects == true 
                    ? standardImageProjects != null 
                    ? standardImageProjects 
                    : standardImage
                    : standardImage;

        var statusOnProject = project.GetPropertyValue<String>("status");
        var status = statusOnProject == "Completed"
                    ? "bg-success"
                    : statusOnProject == "Under development"
                    ? "bg-warning"
                    : statusOnProject == "Initiated"
                    ? "bg-danger"
                    : "bg-secondary";
                
        <!-- PROJECT LIST -->
        <div class="row my-3 bg-light">
            <div class="col-md-4 p-0 articles-projects-list">
                
                <!-- STATUS LABEL -->
                <p class="position-absolute p-2 label text-light m-0 rounded-0 @status">@project.GetPropertyValue("Status")</p>
    
                <!-- PROJECT IMAGE -->
                <a href="@project.Url"><img src="@image.Url" alt="@image.Name"/></a>

            </div> <!-- end of column -->
        
            <!-- PROJECT INFO (Title, Teaser, Read More) -->
            <div class="col-md-8 py-2 articles-projects-info">
            
                <h3><a href="@project.Url">@(project.GetPropertyValue<String>("projectItemTitle"))</a></h3>
                <p class="article-project-dates text-secondary">@project.CreateDate.ToString("d MMM yyyy"), @project.CreateDate.ToString("HH:mm")</p>
                <p class="m-0">@Umbraco.Truncate(project.GetPropertyValue<String>("projectItemContent"), 140, true)</p>
                <a href="@project.Url">Read more</a>
                
            </div> <!-- end of column -->
        </div> <!-- end of row -->
    }
</div> <!-- end of container -->

AarhusWebDevCoop/Views/MacroPartials/Projects/newestCompletedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
// VARIABLES containing project list and images
var numOfProjects = Model.MacroParameters["numOfProjects"];
var standardImageProjects = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImageProjects");
var showStandardImageProjects = Model.Content.Site().GetPropertyValue<Boolean>("showStandardImageProjects");
var standardImage = Model.Content.Site().GetPropertyValue<IPublishedContent>("standardImage");
var completedProjects =
        Model.Content.Site().FirstChild("projectsMain").Children()
        .Where(x => x.IsVisible())
        .Where(x => x.GetPropertyValue<String>("status")=="Completed")
        .OrderBy("CreateDate desc")
        .Take(Convert.ToInt32(numOfProjects));
}

<div class="container-fluid m-0 p-0">
     
    @foreach (var project in completedProjects) {
            
        <!-- Finding the main image and the status of specific project -->    
        var mainImage = project.GetPropertyValue<IPublishedContent>("projectItemMainImage");
        var image = mainImage != null 
                    ? mainImage 
                    : showStandardImageProjects == true 
                    ? standardImageProjects != null 
                    ? standardImageProjects 
                    : standardImage
                    : standardImage;

        var statusOnProject = project.GetPropertyValue<String>("status");
        var status = statusOnProject == "Completed"
                    ? "bg-success"
                    : statusOnProject == "Under development"
                    ? "bg-warning"
                    : statusOnProject == "Initiated"
                    ? "bg-danger"
                    : "bg-secondary";
                
        <!-- PROJECT LIST -->
        <div class="row my-3 projects-bg bg-light">
            <div class="col-md-4 p-0 articles-projects-list">
                
                <!-- STATUS LABEL -->
                <p class="position-absolute p-2 label text-light m-0 rounded-0 @status">@project.GetPropertyValue("Status")</p>
    
                <!-- PROJECT IMAGE -->
                <a href="@project.Url"><img src="@image.Url" alt="@image.Name" /></a>

            </div> <!-- end of column -->
        
            <!-- PROJECT INFO (Title, Teaser, Read More) -->
            <div class="col-md-8 py-2 articles-projects-info">
            
                <h3><a href="@project.Url">@(project.GetPropertyValue<String>("projectItemTitle"))</a></h3>
                <p class="article-project-dates text-secondary">@project.CreateDate.ToString("d MMM yyyy"), @project.CreateDate.ToString("HH:mm")</p>
                <p class="m-0">@Umbraco.Truncate(project.GetPropertyValue<String>("projectItemContent"), 140, true)</p>
                <a href="@project.Url">Read more</a>
                
            </div> <!-- end of column -->
        </div> <!-- end of row -->
    }
</div> <!-- end of container -->

AarhusWebDevCoop/Views/MacroPartials/boardMessages.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
// VARIABLE containing the messages added in the Message Board
var boardMessages =
    Model.Content.Site().FirstChild("messageBoard").Children()
    .Where(x => x.IsVisible())
    .OrderBy("CreateDate desc");
}

<!-- The Messages -->
@foreach(var message in boardMessages) {
    <div class="container p-4 my-4 bg-light border">
        
        <!-- The name of the user and the published date -->
        <div class="text-secondary clearfix">
            <p class="text-left float-left">By @message.GetPropertyValue("mName")</p>
            <p class="text-right float-right">Published @message.CreateDate.ToString("d MMM yyyy") @Html.Raw("@") @message.CreateDate.ToString("HH:mm")</p>
        </div>
        
        <!-- The title and content of the message -->
        <div>
            <h3>@message.GetPropertyValue("mTitle")</h3>
            <p>@message.GetPropertyValue("mMessage")</p>
        </div>
    </div>
    <hr class="mx-3">
}

AarhusWebDevCoop/Views/MacroPartials/codeBlock.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    // VARIABLE containing the content of the parameter
    var writeText = Model.MacroParameters["writeText"];
}

<!-- Purpose: Special styled div to insert into a Rich Text Editor to e.g. create a codeblock -->
<div class="container write-text pb-1 px-3 pt-3 my-2">
    <p>@Html.Raw(writeText)</p>
</div>

AarhusWebDevCoop/Views/MacroPartials/insertGallery.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    // VARIABLE containing the images passed as parameter
    var mediaIds = Model.MacroParameters["mediaIds"] as string;
}

@if (mediaIds != null) {

    <!-- The Gallery -->
    <div class="row">
        @foreach (var mediaId in mediaIds.Split(',')) {

            var media = Umbraco.TypedMedia(mediaId);

            <!-- Choosing specific images -->
            if (media.DocumentTypeAlias == "Image") {
                if(@mediaIds.Split(',').Count() == 1) {
                    @RenderOne(media as Image);
                } else if(@mediaIds.Split(',').Count() == 2) {
                    @RenderTwo(media as Image);
                } else {
                    @RenderMany(media as Image);
                }
            }

            <!-- Choosing a folder with images -->
            foreach (var image in media.Children<Image>()) {
                if(@media.Children.Count() == 1) {
                    @RenderOne(image);
                } else if(@media.Children.Count() == 2) {
                    @RenderTwo(image);
                } else {
                    @RenderMany(image);
                }
            }
        }
    </div>
}

<!-- Helpers to render the gallery depending on one, two or more images -->
@helper RenderOne(Image item) {
    <div class="col-sm-6 offset-sm-3 p-2">
        <a href="@item.Url" target="_blank">
            <img src="@item.GetCropUrl(height: 500, width: 500)" alt="@item.Name" />
        </a>
    </div>
}

@helper RenderTwo(Image item) {
    <div class="col-sm-6 p-2">
        <a href="@item.Url" target="_blank">
            <img src="@item.GetCropUrl(height: 500, width: 500)" alt="@item.Name" />
        </a>
    </div>
}

@helper RenderMany(Image item) {
    <div class="col-sm-6 col-xl-4 p-2">
        <a href="@item.Url" target="_blank">
            <img src="@item.GetCropUrl(height: 500, width: 500)" alt="@item.Name" />
        </a>
    </div>
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="@Umbraco.Field("metaDescription")" />
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Model.Content.Name - Aarhus Web Developer Cooperation</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    
    <!-- Main Navigation -->
    <nav class="navbar navbar-dark nav-pills nav-fill navbar-expand-lg bg-dark text-light">
        @Umbraco.RenderMacro("mainMenu")
    </nav>
    
    <!-- Main Content -->
    <main>
        <!-- The Header -->
        @Umbraco.RenderMacro("header")
        
        <!-- The Content -->
        @RenderBody()
    </main>
    
    <!-- Main Footer -->
    <footer class="main-footer container-fluid bg-dark text-light text-center p-3">
        @Umbraco.Field("footerText", recursive: true)
    </footer>
    
    <!-- Script File References -->
    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/popper.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
</body>
</html>

AarhusWebDevCoop/Views/MessageBoard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MessageBoard>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{ Layout = "Master.cshtml"; }

<article class="my-4">    
    <section>
        <!-- Description of the Message Board Page -->
        <div class="container p-0">
            @Umbraco.Field("messageBoardDescription")
        </div>
        
        <!-- The Message Form (added with Child Action) -->
        <h2>Write a message</h2>
        @Html.Action("Index", "MessageFormSurface")
    </section>
    
    <!-- Adding already sent messages -->
    <section>
        <h2>Messages</h2>
        <p class="text-center">See newest messages</p>
        <hr class="mx-3">
        <div class="container p-0">
            @Umbraco.RenderMacro("boardMessages")
        </div>
    </section>
</article>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>